=== cloudemedia/BrowserDetector/schema/tests.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "minItems": 1,
  "uniqueItems": true,
  "items": {
    "type": "object",
    "properties": {
      "headers": {
        "type": "object",
        "properties": {
          "user-agent": {
            "type": "string"
          }
        }
      },
      "device": {
        "type": "object",
        "properties": {
          "deviceName": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "marketingName": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "manufacturer": {
            "type": "string"
          },
          "brand": {
            "type": "string"
          },
          "pointingMethod": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "resolutionWidth": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ]
          },
          "resolutionHeight": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ]
          },
          "dualOrientation": {
            "type": "boolean"
          },
          "type": {
            "type": "string"
          }
        },
        "required": [
          "deviceName",
          "marketingName",
          "manufacturer",
          "brand",
          "pointingMethod",
          "resolutionWidth",
          "resolutionHeight",
          "dualOrientation",
          "type"
        ]
      },
      "browser": {
        "type": "object",
        "properties": {
          "name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "modus": {
            "anyOf": [
              {
                "type": "null"
              },
              {
                "type": "integer"
              }
            ]
          },
          "version": {
            "type": "string"
          },
          "manufacturer": {
            "type": "string"
          },
          "bits": {
            "type": "integer"
          },
          "type": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "modus",
          "version",
          "manufacturer",
          "bits",
          "type"
        ]
      },
      "os": {
        "type": "object",
        "properties": {
          "name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "marketingName": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "version": {
            "type": "string"
          },
          "manufacturer": {
            "type": "string"
          },
          "bits": {
            "type": "integer"
          }
        },
        "required": [
          "name",
          "marketingName",
          "version",
          "manufacturer",
          "bits"
        ]
      },
      "engine": {
        "type": "object",
        "properties": {
          "name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "version": {
            "type": "string"
          },
          "manufacturer": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "version",
          "manufacturer"
        ]
      }
    },
    "required": [
      "headers",
      "device",
      "browser",
      "os",
      "engine"
    ]
  }
}

=== cloudemedia/BrowserDetector/tests/data/device/mobile/avvio.json
[
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; Android 4.4.2; es-us; Avvio L500 Build/KVT49L) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.114 Mobile Safari/537.36"
    },
    "device": {
      "deviceName": "L500",
      "marketingName": "L500",
      "manufacturer": "Avvio",
      "brand": "Avvio",
      "pointingMethod": "touchscreen",
      "resolutionWidth": 480,
      "resolutionHeight": 854,
      "dualOrientation": true,
      "type": "smartphone"
    },
    "browser": {
      "name": "Chrome",
      "modus": null,
      "version": "34.0.1847.114",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.4.2",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "Blink",
      "version": "537.36.0",
      "manufacturer": "Google"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; U; Android 4.2.2; es-us; AVVIO_765 AVVIO 765 Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30"
    },
    "device": {
      "deviceName": "765",
      "marketingName": "765",
      "manufacturer": "Avvio",
      "brand": "Avvio",
      "pointingMethod": "touchscreen",
      "resolutionWidth": 320,
      "resolutionHeight": 480,
      "dualOrientation": true,
      "type": "smartphone"
    },
    "browser": {
      "name": "Android Webkit",
      "modus": null,
      "version": "4.0.0",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.2.2",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "WebKit",
      "version": "534.30.0",
      "manufacturer": "Apple"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; U; Android 4.2.2; es-us; Avvio_775 Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30"
    },
    "device": {
      "deviceName": "775",
      "marketingName": "775",
      "manufacturer": "Avvio",
      "brand": "Avvio",
      "pointingMethod": "touchscreen",
      "resolutionWidth": 480,
      "resolutionHeight": 800,
      "dualOrientation": true,
      "type": "smartphone"
    },
    "browser": {
      "name": "Android Webkit",
      "modus": null,
      "version": "4.0.0",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.2.2",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "WebKit",
      "version": "534.30.0",
      "manufacturer": "Apple"
    }
  }
]

=== cloudemedia/BrowserDetector/tests/data/device/mobile/mhorse.json
[
  {
    "headers": {
      "user-agent": "UCWEB/2.0 (MIDP-2.0; U; Adr 4.4; en-US; SPHS_on_Hsdroid) U2/1.0.0 UCBrowser/8.9.2.373 U2/1.0.0 Mobile"
    },
    "device": {
      "deviceName": "SPHS On HSDroid",
      "marketingName": "9500mini",
      "manufacturer": "MHorse",
      "brand": "MHorse",
      "pointingMethod": "touchscreen",
      "resolutionWidth": 320,
      "resolutionHeight": 480,
      "dualOrientation": true,
      "type": "smartphone"
    },
    "browser": {
      "name": "UC Browser",
      "modus": null,
      "version": "8.9.2.373",
      "manufacturer": "UcWeb",
      "bits": 32,
      "type": "transcoder"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.4.0",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "U2",
      "version": "1.0.0",
      "manufacturer": "UcWeb"
    }
  }
]

=== cloudemedia/BrowserDetector/tests/data/device/logicpd.json
[
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; U; Android 2.2.1; en-us; Nook Color (zoom2) Build/FROYO) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1"
    },
    "device": {
      "deviceName": "Zoom2",
      "marketingName": "Nook Color",
      "manufacturer": "Logicpd",
      "brand": "BarnesNoble",
      "pointingMethod": "touchscreen",
      "resolutionWidth": 1024,
      "resolutionHeight": 600,
      "dualOrientation": true,
      "type": "tablet"
    },
    "browser": {
      "name": "Android Webkit",
      "modus": null,
      "version": "4.0.0",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "2.2.1",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "WebKit",
      "version": "533.1.0",
      "manufacturer": "Apple"
    }
  }
]

=== cloudemedia/BrowserDetector/tests/data/device/mobile/bluboo.json
[
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; Android 5.1; Picasso Build/LMY47I) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36"
    },
    "device": {
      "deviceName": "Picasso",
      "marketingName": "Picasso",
      "manufacturer": "Bluboo",
      "brand": "Bluboo",
      "pointingMethod": "touchscreen",
      "resolutionWidth": 720,
      "resolutionHeight": 1280,
      "dualOrientation": true,
      "type": "smartphone"
    },
    "browser": {
      "name": "Android WebView",
      "modus": null,
      "version": "39.0.0.0",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "5.1.0",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "Blink",
      "version": "537.36.0",
      "manufacturer": "Google"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; Android 6.0; Bluboo Maya Max Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.68 Mobile Safari/537.36"
    },
    "device": {
      "deviceName": "Maya Max",
      "marketingName": "Maya Max",
      "manufacturer": "Bluboo",
      "brand": "Bluboo",
      "pointingMethod": "touchscreen",
      "resolutionWidth": 720,
      "resolutionHeight": 1280,
      "dualOrientation": true,
      "type": "smartphone"
    },
    "browser": {
      "name": "Chrome",
      "modus": null,
      "version": "67.0.3396.68",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "6.0.0",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "Blink",
      "version": "537.36.0",
      "manufacturer": "Google"
    }
  }
]

=== cloudemedia/BrowserDetector/tests/data/device/mobile/eboda.json
[
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; U; Android 4.2.2; ro-ro; E-Boda Rainbow V47 Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30"
    },
    "device": {
      "deviceName": "Rainbow V47",
      "marketingName": "Rainbow V47",
      "manufacturer": "E-Boda",
      "brand": "E-Boda",
      "pointingMethod": "touchscreen",
      "resolutionWidth": 480,
      "resolutionHeight": 800,
      "dualOrientation": true,
      "type": "smartphone"
    },
    "browser": {
      "name": "Android Webkit",
      "modus": null,
      "version": "4.0.0",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.2.2",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "WebKit",
      "version": "534.30.0",
      "manufacturer": "Apple"
    }
  }
]

=== cloudemedia/BrowserDetector/tests/data/device/mobile/pulid.json
[
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; Android 4.1.1; PULID F11 Build/JRO03C) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.89 Mobile Safari/537.36 OPR/27.0.1698.88647"
    },
    "device": {
      "deviceName": "F11",
      "marketingName": "F11",
      "manufacturer": "Pulid",
      "brand": "Pulid",
      "pointingMethod": "touchscreen",
      "resolutionWidth": 720,
      "resolutionHeight": 1280,
      "dualOrientation": true,
      "type": "smartphone"
    },
    "browser": {
      "name": "Opera Mobile",
      "modus": null,
      "version": "27.0.1698.88647",
      "manufacturer": "Opera",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.1.1",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "Blink",
      "version": "537.36.0",
      "manufacturer": "Google"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; Android 4.1.1; PULID F15 Build/JRO03C) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.89 Mobile Safari/537.36 OPR/27.0.1698.88647"
    },
    "device": {
      "deviceName": "F15",
      "marketingName": "F15",
      "manufacturer": "Pulid",
      "brand": "Pulid",
      "pointingMethod": "touchscreen",
      "resolutionWidth": 720,
      "resolutionHeight": 1280,
      "dualOrientation": true,
      "type": "smartphone"
    },
    "browser": {
      "name": "Opera Mobile",
      "modus": null,
      "version": "27.0.1698.88647",
      "manufacturer": "Opera",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.1.1",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "Blink",
      "version": "537.36.0",
      "manufacturer": "Google"
    }
  }
]

=== cloudemedia/BrowserDetector/tests/data/device/mobile/lanix.json
[
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; Android 4.4.2; Ilium L820 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.136 Mobile Safari/537.36"
    },
    "device": {
      "deviceName": "Ilium L820",
      "marketingName": "Ilium L820",
      "manufacturer": "Lanix",
      "brand": "Lanix",
      "pointingMethod": "touchscreen",
      "resolutionWidth": 480,
      "resolutionHeight": 800,
      "dualOrientation": true,
      "type": "smartphone"
    },
    "browser": {
      "name": "Chrome",
      "modus": null,
      "version": "33.0.1750.136",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.4.2",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "Blink",
      "version": "537.36.0",
      "manufacturer": "Google"
    }
  }
]
